//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
using WebApplication.Extensions;

#line default
#line hidden

#line 2 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
using Vereyon.Web;

#line default
#line hidden

public class _Page_Multiempresas_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Multiempresas_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 3 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Styles.Render("~/AdminLTE/plugins/datatables/css");


#line default
#line hidden

#line 4 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Styles.Render("~/AdminLTE/plugins/datepicker/css");


#line default
#line hidden

#line 5 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Styles.Render("~/AdminLTE/plugins/daterangepicker/css");


#line default
#line hidden

#line 6 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Styles.Render("~/AdminLTE/dist/css");


#line default
#line hidden

#line 7 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Styles.Render("~/AdminLTE/dist/css/skins");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 8 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Scripts.Render("~/AdminLTE/plugins/datatables/js");


#line default
#line hidden

#line 9 "C:\Users\danie\AppData\Local\Temp\A9ABAE931465EBB9644B8C315FEF52CF23BD\2\ERP-master\WebApplication\Views\Contabilidad\Multiempresas.cshtml"
__o = Scripts.Render("~/Scripts/Contabilidad/Multiempresas");


#line default
#line hidden
});

}
}
}
